---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/signup":
    post:
      summary: Create a User
      parameters: []
      responses:
        '200':
          description: user created
        '400':
          description: invaild request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/api/users/{id}":
    get:
      summary: Return a User
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      security:
      - bearerAuth: []
      responses:
        '200':
          description: from the database successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  email:
                    type: string
                  password:
                    type: string
                required:
                - id
                - email
                - password
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  bearerAuth: []
